source 'https://rubygems.org'

gem 'rails', '3.2.22.2'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'


gem "bson_ext"
gem "mongoid", ">= 3.0.0.rc"

gem 'shared_engine', :path => '../shared_engine'
gem 'acts_as_api', :path => '../../'

group :test do
  gem 'rspec-rails', '>= 2.5.0'
  gem 'webrat'
end
