source 'https://rubygems.org'

gem 'rails', '5.0.0.1'

gem 'sqlite3'

gem 'shared_engine', path: '../shared_engine'
gem 'acts_as_api', path: '../../'

group :test do
  gem 'rspec-rails', '>= 2.5.0'
  gem 'webrat'
end
